// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjajnvirtpitancefqjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqYWpudmlydHBpdGFuY2VmcWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODMxMjAsImV4cCI6MjA4NjY1OTEyMH0.e0TQUyFcZDjtq4El0MAJyJ_koHtcyP9684Y4e7Se8ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});